services: docker

language: scala
scala:
  - 2.13.1
jdk: oraclejdk8

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - docker run --publish 389:389 --publish 636:636 --detach --name ldap osixia/openldap

script:
  #- sbt coverage test
  - sbt test

#after_success:
#  - sbt coverageReport codacyCoverage